AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'config/environments/**/*.rb'
    - 'spec/**/*.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
